plugins {
    id 'java'
    id 'application' 
    id 'com.google.protobuf' version '0.9.4'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

group = 'com.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral() 
}

dependencies {
    implementation 'com.google.protobuf:protobuf-java:3.25.1'
}

// Configure JavaFX modules and version
javafx {
    version = "21" 
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}

// Define the main class for the application plugin
application {
    mainClass = 'ApplicationFX.MainSummerApp'
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:3.25.1"
    }
    generateProtoTasks {
        all().each { task -> }
    }
}

sourceSets {
    main {
        java {
            srcDirs 'src/main/java'
            srcDirs 'build/generated/source/proto/main/java'
        }
    }
}