// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: CardWrapper.proto
// Protobuf Java Version: 4.34.1

package ProtoMessages;

@com.google.protobuf.Generated
public final class CardWrapperProto extends com.google.protobuf.GeneratedFile {
  private CardWrapperProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "CardWrapperProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CardWrapperOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProtoMessages.CardWrapper)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ProtoMessages.ScriptCard scriptCard = 1;</code>
     * @return Whether the scriptCard field is set.
     */
    boolean hasScriptCard();
    /**
     * <code>.ProtoMessages.ScriptCard scriptCard = 1;</code>
     * @return The scriptCard.
     */
    ProtoMessages.ScriptCardOuterClass.ScriptCard getScriptCard();
    /**
     * <code>.ProtoMessages.ScriptCard scriptCard = 1;</code>
     */
    ProtoMessages.ScriptCardOuterClass.ScriptCardOrBuilder getScriptCardOrBuilder();

    /**
     * <code>.ProtoMessages.DeviceCard deviceCard = 2;</code>
     * @return Whether the deviceCard field is set.
     */
    boolean hasDeviceCard();
    /**
     * <code>.ProtoMessages.DeviceCard deviceCard = 2;</code>
     * @return The deviceCard.
     */
    ProtoMessages.DeviceCardOuterClass.DeviceCard getDeviceCard();
    /**
     * <code>.ProtoMessages.DeviceCard deviceCard = 2;</code>
     */
    ProtoMessages.DeviceCardOuterClass.DeviceCardOrBuilder getDeviceCardOrBuilder();

    /**
     * <code>.ProtoMessages.ComponentCard componentCard = 3;</code>
     * @return Whether the componentCard field is set.
     */
    boolean hasComponentCard();
    /**
     * <code>.ProtoMessages.ComponentCard componentCard = 3;</code>
     * @return The componentCard.
     */
    ProtoMessages.ComponentCardOuterClass.ComponentCard getComponentCard();
    /**
     * <code>.ProtoMessages.ComponentCard componentCard = 3;</code>
     */
    ProtoMessages.ComponentCardOuterClass.ComponentCardOrBuilder getComponentCardOrBuilder();

    ProtoMessages.CardWrapperProto.CardWrapper.CardCase getCardCase();
  }
  /**
   * Protobuf type {@code ProtoMessages.CardWrapper}
   */
  public static final class CardWrapper extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ProtoMessages.CardWrapper)
      CardWrapperOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 34,
        /* patch= */ 1,
        /* suffix= */ "",
        "CardWrapper");
    }
    // Use CardWrapper.newBuilder() to construct.
    private CardWrapper(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CardWrapper() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoMessages.CardWrapperProto.internal_static_ProtoMessages_CardWrapper_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return ProtoMessages.CardWrapperProto.internal_static_ProtoMessages_CardWrapper_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoMessages.CardWrapperProto.internal_static_ProtoMessages_CardWrapper_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoMessages.CardWrapperProto.CardWrapper.class, ProtoMessages.CardWrapperProto.CardWrapper.Builder.class);
    }

    private int cardCase_ = 0;
    @SuppressWarnings("serial")
    private java.lang.Object card_;
    public enum CardCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      SCRIPTCARD(1),
      DEVICECARD(2),
      COMPONENTCARD(3),
      CARD_NOT_SET(0);
      private final int value;
      private CardCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static CardCase valueOf(int value) {
        return forNumber(value);
      }

      public static CardCase forNumber(int value) {
        switch (value) {
          case 1: return SCRIPTCARD;
          case 2: return DEVICECARD;
          case 3: return COMPONENTCARD;
          case 0: return CARD_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public CardCase
    getCardCase() {
      return CardCase.forNumber(
          cardCase_);
    }

    public static final int SCRIPTCARD_FIELD_NUMBER = 1;
    /**
     * <code>.ProtoMessages.ScriptCard scriptCard = 1;</code>
     * @return Whether the scriptCard field is set.
     */
    @java.lang.Override
    public boolean hasScriptCard() {
      return cardCase_ == 1;
    }
    /**
     * <code>.ProtoMessages.ScriptCard scriptCard = 1;</code>
     * @return The scriptCard.
     */
    @java.lang.Override
    public ProtoMessages.ScriptCardOuterClass.ScriptCard getScriptCard() {
      if (cardCase_ == 1) {
         return (ProtoMessages.ScriptCardOuterClass.ScriptCard) card_;
      }
      return ProtoMessages.ScriptCardOuterClass.ScriptCard.getDefaultInstance();
    }
    /**
     * <code>.ProtoMessages.ScriptCard scriptCard = 1;</code>
     */
    @java.lang.Override
    public ProtoMessages.ScriptCardOuterClass.ScriptCardOrBuilder getScriptCardOrBuilder() {
      if (cardCase_ == 1) {
         return (ProtoMessages.ScriptCardOuterClass.ScriptCard) card_;
      }
      return ProtoMessages.ScriptCardOuterClass.ScriptCard.getDefaultInstance();
    }

    public static final int DEVICECARD_FIELD_NUMBER = 2;
    /**
     * <code>.ProtoMessages.DeviceCard deviceCard = 2;</code>
     * @return Whether the deviceCard field is set.
     */
    @java.lang.Override
    public boolean hasDeviceCard() {
      return cardCase_ == 2;
    }
    /**
     * <code>.ProtoMessages.DeviceCard deviceCard = 2;</code>
     * @return The deviceCard.
     */
    @java.lang.Override
    public ProtoMessages.DeviceCardOuterClass.DeviceCard getDeviceCard() {
      if (cardCase_ == 2) {
         return (ProtoMessages.DeviceCardOuterClass.DeviceCard) card_;
      }
      return ProtoMessages.DeviceCardOuterClass.DeviceCard.getDefaultInstance();
    }
    /**
     * <code>.ProtoMessages.DeviceCard deviceCard = 2;</code>
     */
    @java.lang.Override
    public ProtoMessages.DeviceCardOuterClass.DeviceCardOrBuilder getDeviceCardOrBuilder() {
      if (cardCase_ == 2) {
         return (ProtoMessages.DeviceCardOuterClass.DeviceCard) card_;
      }
      return ProtoMessages.DeviceCardOuterClass.DeviceCard.getDefaultInstance();
    }

    public static final int COMPONENTCARD_FIELD_NUMBER = 3;
    /**
     * <code>.ProtoMessages.ComponentCard componentCard = 3;</code>
     * @return Whether the componentCard field is set.
     */
    @java.lang.Override
    public boolean hasComponentCard() {
      return cardCase_ == 3;
    }
    /**
     * <code>.ProtoMessages.ComponentCard componentCard = 3;</code>
     * @return The componentCard.
     */
    @java.lang.Override
    public ProtoMessages.ComponentCardOuterClass.ComponentCard getComponentCard() {
      if (cardCase_ == 3) {
         return (ProtoMessages.ComponentCardOuterClass.ComponentCard) card_;
      }
      return ProtoMessages.ComponentCardOuterClass.ComponentCard.getDefaultInstance();
    }
    /**
     * <code>.ProtoMessages.ComponentCard componentCard = 3;</code>
     */
    @java.lang.Override
    public ProtoMessages.ComponentCardOuterClass.ComponentCardOrBuilder getComponentCardOrBuilder() {
      if (cardCase_ == 3) {
         return (ProtoMessages.ComponentCardOuterClass.ComponentCard) card_;
      }
      return ProtoMessages.ComponentCardOuterClass.ComponentCard.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cardCase_ == 1) {
        output.writeMessage(1, (ProtoMessages.ScriptCardOuterClass.ScriptCard) card_);
      }
      if (cardCase_ == 2) {
        output.writeMessage(2, (ProtoMessages.DeviceCardOuterClass.DeviceCard) card_);
      }
      if (cardCase_ == 3) {
        output.writeMessage(3, (ProtoMessages.ComponentCardOuterClass.ComponentCard) card_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cardCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (ProtoMessages.ScriptCardOuterClass.ScriptCard) card_);
      }
      if (cardCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (ProtoMessages.DeviceCardOuterClass.DeviceCard) card_);
      }
      if (cardCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (ProtoMessages.ComponentCardOuterClass.ComponentCard) card_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProtoMessages.CardWrapperProto.CardWrapper)) {
        return super.equals(obj);
      }
      ProtoMessages.CardWrapperProto.CardWrapper other = (ProtoMessages.CardWrapperProto.CardWrapper) obj;

      if (!getCardCase().equals(other.getCardCase())) return false;
      switch (cardCase_) {
        case 1:
          if (!getScriptCard()
              .equals(other.getScriptCard())) return false;
          break;
        case 2:
          if (!getDeviceCard()
              .equals(other.getDeviceCard())) return false;
          break;
        case 3:
          if (!getComponentCard()
              .equals(other.getComponentCard())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (cardCase_) {
        case 1:
          hash = (37 * hash) + SCRIPTCARD_FIELD_NUMBER;
          hash = (53 * hash) + getScriptCard().hashCode();
          break;
        case 2:
          hash = (37 * hash) + DEVICECARD_FIELD_NUMBER;
          hash = (53 * hash) + getDeviceCard().hashCode();
          break;
        case 3:
          hash = (37 * hash) + COMPONENTCARD_FIELD_NUMBER;
          hash = (53 * hash) + getComponentCard().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProtoMessages.CardWrapperProto.CardWrapper parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoMessages.CardWrapperProto.CardWrapper parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoMessages.CardWrapperProto.CardWrapper parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoMessages.CardWrapperProto.CardWrapper parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoMessages.CardWrapperProto.CardWrapper parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoMessages.CardWrapperProto.CardWrapper parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoMessages.CardWrapperProto.CardWrapper parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ProtoMessages.CardWrapperProto.CardWrapper parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ProtoMessages.CardWrapperProto.CardWrapper parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ProtoMessages.CardWrapperProto.CardWrapper parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoMessages.CardWrapperProto.CardWrapper parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ProtoMessages.CardWrapperProto.CardWrapper parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtoMessages.CardWrapperProto.CardWrapper prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProtoMessages.CardWrapper}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProtoMessages.CardWrapper)
        ProtoMessages.CardWrapperProto.CardWrapperOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoMessages.CardWrapperProto.internal_static_ProtoMessages_CardWrapper_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoMessages.CardWrapperProto.internal_static_ProtoMessages_CardWrapper_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoMessages.CardWrapperProto.CardWrapper.class, ProtoMessages.CardWrapperProto.CardWrapper.Builder.class);
      }

      // Construct using ProtoMessages.CardWrapperProto.CardWrapper.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (scriptCardBuilder_ != null) {
          scriptCardBuilder_.clear();
        }
        if (deviceCardBuilder_ != null) {
          deviceCardBuilder_.clear();
        }
        if (componentCardBuilder_ != null) {
          componentCardBuilder_.clear();
        }
        cardCase_ = 0;
        card_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoMessages.CardWrapperProto.internal_static_ProtoMessages_CardWrapper_descriptor;
      }

      @java.lang.Override
      public ProtoMessages.CardWrapperProto.CardWrapper getDefaultInstanceForType() {
        return ProtoMessages.CardWrapperProto.CardWrapper.getDefaultInstance();
      }

      @java.lang.Override
      public ProtoMessages.CardWrapperProto.CardWrapper build() {
        ProtoMessages.CardWrapperProto.CardWrapper result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ProtoMessages.CardWrapperProto.CardWrapper buildPartial() {
        ProtoMessages.CardWrapperProto.CardWrapper result = new ProtoMessages.CardWrapperProto.CardWrapper(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(ProtoMessages.CardWrapperProto.CardWrapper result) {
        int from_bitField0_ = bitField0_;
      }

      private void buildPartialOneofs(ProtoMessages.CardWrapperProto.CardWrapper result) {
        result.cardCase_ = cardCase_;
        result.card_ = this.card_;
        if (cardCase_ == 1 &&
            scriptCardBuilder_ != null) {
          result.card_ = scriptCardBuilder_.build();
        }
        if (cardCase_ == 2 &&
            deviceCardBuilder_ != null) {
          result.card_ = deviceCardBuilder_.build();
        }
        if (cardCase_ == 3 &&
            componentCardBuilder_ != null) {
          result.card_ = componentCardBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoMessages.CardWrapperProto.CardWrapper) {
          return mergeFrom((ProtoMessages.CardWrapperProto.CardWrapper)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoMessages.CardWrapperProto.CardWrapper other) {
        if (other == ProtoMessages.CardWrapperProto.CardWrapper.getDefaultInstance()) return this;
        switch (other.getCardCase()) {
          case SCRIPTCARD: {
            mergeScriptCard(other.getScriptCard());
            break;
          }
          case DEVICECARD: {
            mergeDeviceCard(other.getDeviceCard());
            break;
          }
          case COMPONENTCARD: {
            mergeComponentCard(other.getComponentCard());
            break;
          }
          case CARD_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    internalGetScriptCardFieldBuilder().getBuilder(),
                    extensionRegistry);
                cardCase_ = 1;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    internalGetDeviceCardFieldBuilder().getBuilder(),
                    extensionRegistry);
                cardCase_ = 2;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    internalGetComponentCardFieldBuilder().getBuilder(),
                    extensionRegistry);
                cardCase_ = 3;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int cardCase_ = 0;
      private java.lang.Object card_;
      public CardCase
          getCardCase() {
        return CardCase.forNumber(
            cardCase_);
      }

      public Builder clearCard() {
        cardCase_ = 0;
        card_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.SingleFieldBuilder<
          ProtoMessages.ScriptCardOuterClass.ScriptCard, ProtoMessages.ScriptCardOuterClass.ScriptCard.Builder, ProtoMessages.ScriptCardOuterClass.ScriptCardOrBuilder> scriptCardBuilder_;
      /**
       * <code>.ProtoMessages.ScriptCard scriptCard = 1;</code>
       * @return Whether the scriptCard field is set.
       */
      @java.lang.Override
      public boolean hasScriptCard() {
        return cardCase_ == 1;
      }
      /**
       * <code>.ProtoMessages.ScriptCard scriptCard = 1;</code>
       * @return The scriptCard.
       */
      @java.lang.Override
      public ProtoMessages.ScriptCardOuterClass.ScriptCard getScriptCard() {
        if (scriptCardBuilder_ == null) {
          if (cardCase_ == 1) {
            return (ProtoMessages.ScriptCardOuterClass.ScriptCard) card_;
          }
          return ProtoMessages.ScriptCardOuterClass.ScriptCard.getDefaultInstance();
        } else {
          if (cardCase_ == 1) {
            return scriptCardBuilder_.getMessage();
          }
          return ProtoMessages.ScriptCardOuterClass.ScriptCard.getDefaultInstance();
        }
      }
      /**
       * <code>.ProtoMessages.ScriptCard scriptCard = 1;</code>
       */
      public Builder setScriptCard(ProtoMessages.ScriptCardOuterClass.ScriptCard value) {
        if (scriptCardBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          card_ = value;
          onChanged();
        } else {
          scriptCardBuilder_.setMessage(value);
        }
        cardCase_ = 1;
        return this;
      }
      /**
       * <code>.ProtoMessages.ScriptCard scriptCard = 1;</code>
       */
      public Builder setScriptCard(
          ProtoMessages.ScriptCardOuterClass.ScriptCard.Builder builderForValue) {
        if (scriptCardBuilder_ == null) {
          card_ = builderForValue.build();
          onChanged();
        } else {
          scriptCardBuilder_.setMessage(builderForValue.build());
        }
        cardCase_ = 1;
        return this;
      }
      /**
       * <code>.ProtoMessages.ScriptCard scriptCard = 1;</code>
       */
      public Builder mergeScriptCard(ProtoMessages.ScriptCardOuterClass.ScriptCard value) {
        if (scriptCardBuilder_ == null) {
          if (cardCase_ == 1 &&
              card_ != ProtoMessages.ScriptCardOuterClass.ScriptCard.getDefaultInstance()) {
            card_ = ProtoMessages.ScriptCardOuterClass.ScriptCard.newBuilder((ProtoMessages.ScriptCardOuterClass.ScriptCard) card_)
                .mergeFrom(value).buildPartial();
          } else {
            card_ = value;
          }
          onChanged();
        } else {
          if (cardCase_ == 1) {
            scriptCardBuilder_.mergeFrom(value);
          } else {
            scriptCardBuilder_.setMessage(value);
          }
        }
        cardCase_ = 1;
        return this;
      }
      /**
       * <code>.ProtoMessages.ScriptCard scriptCard = 1;</code>
       */
      public Builder clearScriptCard() {
        if (scriptCardBuilder_ == null) {
          if (cardCase_ == 1) {
            cardCase_ = 0;
            card_ = null;
            onChanged();
          }
        } else {
          if (cardCase_ == 1) {
            cardCase_ = 0;
            card_ = null;
          }
          scriptCardBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.ProtoMessages.ScriptCard scriptCard = 1;</code>
       */
      public ProtoMessages.ScriptCardOuterClass.ScriptCard.Builder getScriptCardBuilder() {
        return internalGetScriptCardFieldBuilder().getBuilder();
      }
      /**
       * <code>.ProtoMessages.ScriptCard scriptCard = 1;</code>
       */
      @java.lang.Override
      public ProtoMessages.ScriptCardOuterClass.ScriptCardOrBuilder getScriptCardOrBuilder() {
        if ((cardCase_ == 1) && (scriptCardBuilder_ != null)) {
          return scriptCardBuilder_.getMessageOrBuilder();
        } else {
          if (cardCase_ == 1) {
            return (ProtoMessages.ScriptCardOuterClass.ScriptCard) card_;
          }
          return ProtoMessages.ScriptCardOuterClass.ScriptCard.getDefaultInstance();
        }
      }
      /**
       * <code>.ProtoMessages.ScriptCard scriptCard = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          ProtoMessages.ScriptCardOuterClass.ScriptCard, ProtoMessages.ScriptCardOuterClass.ScriptCard.Builder, ProtoMessages.ScriptCardOuterClass.ScriptCardOrBuilder> 
          internalGetScriptCardFieldBuilder() {
        if (scriptCardBuilder_ == null) {
          if (!(cardCase_ == 1)) {
            card_ = ProtoMessages.ScriptCardOuterClass.ScriptCard.getDefaultInstance();
          }
          scriptCardBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              ProtoMessages.ScriptCardOuterClass.ScriptCard, ProtoMessages.ScriptCardOuterClass.ScriptCard.Builder, ProtoMessages.ScriptCardOuterClass.ScriptCardOrBuilder>(
                  (ProtoMessages.ScriptCardOuterClass.ScriptCard) card_,
                  getParentForChildren(),
                  isClean());
          card_ = null;
        }
        cardCase_ = 1;
        onChanged();
        return scriptCardBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          ProtoMessages.DeviceCardOuterClass.DeviceCard, ProtoMessages.DeviceCardOuterClass.DeviceCard.Builder, ProtoMessages.DeviceCardOuterClass.DeviceCardOrBuilder> deviceCardBuilder_;
      /**
       * <code>.ProtoMessages.DeviceCard deviceCard = 2;</code>
       * @return Whether the deviceCard field is set.
       */
      @java.lang.Override
      public boolean hasDeviceCard() {
        return cardCase_ == 2;
      }
      /**
       * <code>.ProtoMessages.DeviceCard deviceCard = 2;</code>
       * @return The deviceCard.
       */
      @java.lang.Override
      public ProtoMessages.DeviceCardOuterClass.DeviceCard getDeviceCard() {
        if (deviceCardBuilder_ == null) {
          if (cardCase_ == 2) {
            return (ProtoMessages.DeviceCardOuterClass.DeviceCard) card_;
          }
          return ProtoMessages.DeviceCardOuterClass.DeviceCard.getDefaultInstance();
        } else {
          if (cardCase_ == 2) {
            return deviceCardBuilder_.getMessage();
          }
          return ProtoMessages.DeviceCardOuterClass.DeviceCard.getDefaultInstance();
        }
      }
      /**
       * <code>.ProtoMessages.DeviceCard deviceCard = 2;</code>
       */
      public Builder setDeviceCard(ProtoMessages.DeviceCardOuterClass.DeviceCard value) {
        if (deviceCardBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          card_ = value;
          onChanged();
        } else {
          deviceCardBuilder_.setMessage(value);
        }
        cardCase_ = 2;
        return this;
      }
      /**
       * <code>.ProtoMessages.DeviceCard deviceCard = 2;</code>
       */
      public Builder setDeviceCard(
          ProtoMessages.DeviceCardOuterClass.DeviceCard.Builder builderForValue) {
        if (deviceCardBuilder_ == null) {
          card_ = builderForValue.build();
          onChanged();
        } else {
          deviceCardBuilder_.setMessage(builderForValue.build());
        }
        cardCase_ = 2;
        return this;
      }
      /**
       * <code>.ProtoMessages.DeviceCard deviceCard = 2;</code>
       */
      public Builder mergeDeviceCard(ProtoMessages.DeviceCardOuterClass.DeviceCard value) {
        if (deviceCardBuilder_ == null) {
          if (cardCase_ == 2 &&
              card_ != ProtoMessages.DeviceCardOuterClass.DeviceCard.getDefaultInstance()) {
            card_ = ProtoMessages.DeviceCardOuterClass.DeviceCard.newBuilder((ProtoMessages.DeviceCardOuterClass.DeviceCard) card_)
                .mergeFrom(value).buildPartial();
          } else {
            card_ = value;
          }
          onChanged();
        } else {
          if (cardCase_ == 2) {
            deviceCardBuilder_.mergeFrom(value);
          } else {
            deviceCardBuilder_.setMessage(value);
          }
        }
        cardCase_ = 2;
        return this;
      }
      /**
       * <code>.ProtoMessages.DeviceCard deviceCard = 2;</code>
       */
      public Builder clearDeviceCard() {
        if (deviceCardBuilder_ == null) {
          if (cardCase_ == 2) {
            cardCase_ = 0;
            card_ = null;
            onChanged();
          }
        } else {
          if (cardCase_ == 2) {
            cardCase_ = 0;
            card_ = null;
          }
          deviceCardBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.ProtoMessages.DeviceCard deviceCard = 2;</code>
       */
      public ProtoMessages.DeviceCardOuterClass.DeviceCard.Builder getDeviceCardBuilder() {
        return internalGetDeviceCardFieldBuilder().getBuilder();
      }
      /**
       * <code>.ProtoMessages.DeviceCard deviceCard = 2;</code>
       */
      @java.lang.Override
      public ProtoMessages.DeviceCardOuterClass.DeviceCardOrBuilder getDeviceCardOrBuilder() {
        if ((cardCase_ == 2) && (deviceCardBuilder_ != null)) {
          return deviceCardBuilder_.getMessageOrBuilder();
        } else {
          if (cardCase_ == 2) {
            return (ProtoMessages.DeviceCardOuterClass.DeviceCard) card_;
          }
          return ProtoMessages.DeviceCardOuterClass.DeviceCard.getDefaultInstance();
        }
      }
      /**
       * <code>.ProtoMessages.DeviceCard deviceCard = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          ProtoMessages.DeviceCardOuterClass.DeviceCard, ProtoMessages.DeviceCardOuterClass.DeviceCard.Builder, ProtoMessages.DeviceCardOuterClass.DeviceCardOrBuilder> 
          internalGetDeviceCardFieldBuilder() {
        if (deviceCardBuilder_ == null) {
          if (!(cardCase_ == 2)) {
            card_ = ProtoMessages.DeviceCardOuterClass.DeviceCard.getDefaultInstance();
          }
          deviceCardBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              ProtoMessages.DeviceCardOuterClass.DeviceCard, ProtoMessages.DeviceCardOuterClass.DeviceCard.Builder, ProtoMessages.DeviceCardOuterClass.DeviceCardOrBuilder>(
                  (ProtoMessages.DeviceCardOuterClass.DeviceCard) card_,
                  getParentForChildren(),
                  isClean());
          card_ = null;
        }
        cardCase_ = 2;
        onChanged();
        return deviceCardBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          ProtoMessages.ComponentCardOuterClass.ComponentCard, ProtoMessages.ComponentCardOuterClass.ComponentCard.Builder, ProtoMessages.ComponentCardOuterClass.ComponentCardOrBuilder> componentCardBuilder_;
      /**
       * <code>.ProtoMessages.ComponentCard componentCard = 3;</code>
       * @return Whether the componentCard field is set.
       */
      @java.lang.Override
      public boolean hasComponentCard() {
        return cardCase_ == 3;
      }
      /**
       * <code>.ProtoMessages.ComponentCard componentCard = 3;</code>
       * @return The componentCard.
       */
      @java.lang.Override
      public ProtoMessages.ComponentCardOuterClass.ComponentCard getComponentCard() {
        if (componentCardBuilder_ == null) {
          if (cardCase_ == 3) {
            return (ProtoMessages.ComponentCardOuterClass.ComponentCard) card_;
          }
          return ProtoMessages.ComponentCardOuterClass.ComponentCard.getDefaultInstance();
        } else {
          if (cardCase_ == 3) {
            return componentCardBuilder_.getMessage();
          }
          return ProtoMessages.ComponentCardOuterClass.ComponentCard.getDefaultInstance();
        }
      }
      /**
       * <code>.ProtoMessages.ComponentCard componentCard = 3;</code>
       */
      public Builder setComponentCard(ProtoMessages.ComponentCardOuterClass.ComponentCard value) {
        if (componentCardBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          card_ = value;
          onChanged();
        } else {
          componentCardBuilder_.setMessage(value);
        }
        cardCase_ = 3;
        return this;
      }
      /**
       * <code>.ProtoMessages.ComponentCard componentCard = 3;</code>
       */
      public Builder setComponentCard(
          ProtoMessages.ComponentCardOuterClass.ComponentCard.Builder builderForValue) {
        if (componentCardBuilder_ == null) {
          card_ = builderForValue.build();
          onChanged();
        } else {
          componentCardBuilder_.setMessage(builderForValue.build());
        }
        cardCase_ = 3;
        return this;
      }
      /**
       * <code>.ProtoMessages.ComponentCard componentCard = 3;</code>
       */
      public Builder mergeComponentCard(ProtoMessages.ComponentCardOuterClass.ComponentCard value) {
        if (componentCardBuilder_ == null) {
          if (cardCase_ == 3 &&
              card_ != ProtoMessages.ComponentCardOuterClass.ComponentCard.getDefaultInstance()) {
            card_ = ProtoMessages.ComponentCardOuterClass.ComponentCard.newBuilder((ProtoMessages.ComponentCardOuterClass.ComponentCard) card_)
                .mergeFrom(value).buildPartial();
          } else {
            card_ = value;
          }
          onChanged();
        } else {
          if (cardCase_ == 3) {
            componentCardBuilder_.mergeFrom(value);
          } else {
            componentCardBuilder_.setMessage(value);
          }
        }
        cardCase_ = 3;
        return this;
      }
      /**
       * <code>.ProtoMessages.ComponentCard componentCard = 3;</code>
       */
      public Builder clearComponentCard() {
        if (componentCardBuilder_ == null) {
          if (cardCase_ == 3) {
            cardCase_ = 0;
            card_ = null;
            onChanged();
          }
        } else {
          if (cardCase_ == 3) {
            cardCase_ = 0;
            card_ = null;
          }
          componentCardBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.ProtoMessages.ComponentCard componentCard = 3;</code>
       */
      public ProtoMessages.ComponentCardOuterClass.ComponentCard.Builder getComponentCardBuilder() {
        return internalGetComponentCardFieldBuilder().getBuilder();
      }
      /**
       * <code>.ProtoMessages.ComponentCard componentCard = 3;</code>
       */
      @java.lang.Override
      public ProtoMessages.ComponentCardOuterClass.ComponentCardOrBuilder getComponentCardOrBuilder() {
        if ((cardCase_ == 3) && (componentCardBuilder_ != null)) {
          return componentCardBuilder_.getMessageOrBuilder();
        } else {
          if (cardCase_ == 3) {
            return (ProtoMessages.ComponentCardOuterClass.ComponentCard) card_;
          }
          return ProtoMessages.ComponentCardOuterClass.ComponentCard.getDefaultInstance();
        }
      }
      /**
       * <code>.ProtoMessages.ComponentCard componentCard = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          ProtoMessages.ComponentCardOuterClass.ComponentCard, ProtoMessages.ComponentCardOuterClass.ComponentCard.Builder, ProtoMessages.ComponentCardOuterClass.ComponentCardOrBuilder> 
          internalGetComponentCardFieldBuilder() {
        if (componentCardBuilder_ == null) {
          if (!(cardCase_ == 3)) {
            card_ = ProtoMessages.ComponentCardOuterClass.ComponentCard.getDefaultInstance();
          }
          componentCardBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              ProtoMessages.ComponentCardOuterClass.ComponentCard, ProtoMessages.ComponentCardOuterClass.ComponentCard.Builder, ProtoMessages.ComponentCardOuterClass.ComponentCardOrBuilder>(
                  (ProtoMessages.ComponentCardOuterClass.ComponentCard) card_,
                  getParentForChildren(),
                  isClean());
          card_ = null;
        }
        cardCase_ = 3;
        onChanged();
        return componentCardBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ProtoMessages.CardWrapper)
    }

    // @@protoc_insertion_point(class_scope:ProtoMessages.CardWrapper)
    private static final ProtoMessages.CardWrapperProto.CardWrapper DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtoMessages.CardWrapperProto.CardWrapper();
    }

    public static ProtoMessages.CardWrapperProto.CardWrapper getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CardWrapper>
        PARSER = new com.google.protobuf.AbstractParser<CardWrapper>() {
      @java.lang.Override
      public CardWrapper parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CardWrapper> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CardWrapper> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ProtoMessages.CardWrapperProto.CardWrapper getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoMessages_CardWrapper_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtoMessages_CardWrapper_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021CardWrapper.proto\022\rProtoMessages\032\020Scri" +
      "ptCard.proto\032\020DeviceCard.proto\032\023Componen" +
      "tCard.proto\"\256\001\n\013CardWrapper\022/\n\nscriptCar" +
      "d\030\001 \001(\0132\031.ProtoMessages.ScriptCardH\000\022/\n\n" +
      "deviceCard\030\002 \001(\0132\031.ProtoMessages.DeviceC" +
      "ardH\000\0225\n\rcomponentCard\030\003 \001(\0132\034.ProtoMess" +
      "ages.ComponentCardH\000B\006\n\004cardB\022B\020CardWrap" +
      "perProto"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ProtoMessages.ScriptCardOuterClass.getDescriptor(),
          ProtoMessages.DeviceCardOuterClass.getDescriptor(),
          ProtoMessages.ComponentCardOuterClass.getDescriptor(),
        });
    internal_static_ProtoMessages_CardWrapper_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_ProtoMessages_CardWrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ProtoMessages_CardWrapper_descriptor,
        new java.lang.String[] { "ScriptCard", "DeviceCard", "ComponentCard", "Card", });
    descriptor.resolveAllFeaturesImmutable();
    ProtoMessages.ScriptCardOuterClass.getDescriptor();
    ProtoMessages.DeviceCardOuterClass.getDescriptor();
    ProtoMessages.ComponentCardOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
